import React, { useState, useEffect } from 'react';
import { Bell, ShieldAlert, CheckCircle2, Filter, Search, AlertTriangle, RefreshCw } from 'lucide-react';
import { api } from '../services/api';
import { AlertRecord } from '../types';

export const Alerts: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertRecord[]>([]);
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [loading, setLoading] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<AlertRecord | null>(null);

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await api.listAlerts(statusFilter, severityFilter);
      setAlerts(data);
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, [statusFilter, severityFilter]);

  const handleStatusUpdate = async (alertId: string, newStatus: string) => {
    try {
      await api.patchAlert(alertId, newStatus);
      loadAlerts();
      if (selectedAlert && selectedAlert.alert_id === alertId) {
        setSelectedAlert({ ...selectedAlert, status: newStatus as any });
      }
    } catch (err) {
      console.error('Failed to update alert status:', err);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-white flex items-center gap-2">
            <Bell className="w-5 h-5 text-rose-400" />
            <span>Cybersecurity Incident Response & Alert Management</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time security alerts generated by deterministic quantum measurement discrepancies, replay attempts, and identity mismatches.
          </p>
        </div>

        <button
          onClick={loadAlerts}
          disabled={loading}
          className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs flex items-center gap-1.5 transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>Refresh Feed</span>
        </button>
      </div>

      {/* Filter Toolbar */}
      <div className="cyber-card flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 text-xs text-slate-400">
            <Filter className="w-3.5 h-3.5" />
            <span>Status:</span>
          </div>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-xs text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Statuses</option>
            <option value="ACTIVE">ACTIVE</option>
            <option value="INVESTIGATING">INVESTIGATING</option>
            <option value="RESOLVED">RESOLVED</option>
          </select>

          <div className="flex items-center gap-1.5 text-xs text-slate-400 ml-2">
            <span>Severity:</span>
          </div>
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-xs text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>
        </div>

        <div className="text-xs text-slate-400 font-mono">
          Showing {alerts.length} incident alert{alerts.length === 1 ? '' : 's'}
        </div>
      </div>

      {/* Alerts Table & Detail Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Table List */}
        <div className="lg:col-span-2 cyber-card overflow-hidden p-0">
          <div className="overflow-x-auto max-h-[600px]">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-slate-950 text-slate-400 text-[11px] sticky top-0">
                <tr>
                  <th className="p-3">Alert ID</th>
                  <th className="p-3">Severity</th>
                  <th className="p-3">Threat Vector</th>
                  <th className="p-3">Status</th>
                  <th className="p-3">Timestamp</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {alerts.map((alt) => (
                  <tr
                    key={alt.alert_id}
                    onClick={() => setSelectedAlert(alt)}
                    className={`cursor-pointer transition-colors ${
                      selectedAlert?.alert_id === alt.alert_id
                        ? 'bg-cyan-950/40 border-l-2 border-cyan-400'
                        : 'hover:bg-slate-900/60'
                    }`}
                  >
                    <td className="p-3 font-bold text-slate-200">{alt.alert_id}</td>
                    <td className="p-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          alt.severity === 'CRITICAL'
                            ? 'bg-rose-950 text-rose-300 border border-rose-500/40'
                            : alt.severity === 'HIGH'
                            ? 'bg-amber-950 text-amber-300 border border-amber-500/40'
                            : 'bg-slate-800 text-slate-300'
                        }`}
                      >
                        {alt.severity}
                      </span>
                    </td>
                    <td className="p-3 text-cyan-300">{alt.threat_type}</td>
                    <td className="p-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] ${
                          alt.status === 'ACTIVE'
                            ? 'text-rose-400 bg-rose-950/60'
                            : alt.status === 'RESOLVED'
                            ? 'text-emerald-400 bg-emerald-950/60'
                            : 'text-amber-400 bg-amber-950/60'
                        }`}
                      >
                        {alt.status}
                      </span>
                    </td>
                    <td className="p-3 text-slate-500 text-[10px]">
                      {new Date(alt.created_at).toLocaleTimeString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Selected Alert Details */}
        <div className="cyber-card flex flex-col justify-between space-y-4">
          {selectedAlert ? (
            <div className="space-y-4 font-mono text-xs">
              <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                <span className="text-slate-400 text-[10px] uppercase">Incident Inspection</span>
                <span
                  className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    selectedAlert.severity === 'CRITICAL'
                      ? 'bg-rose-950 text-rose-300'
                      : 'bg-amber-950 text-amber-300'
                  }`}
                >
                  {selectedAlert.severity}
                </span>
              </div>

              <div>
                <h3 className="text-sm font-bold text-white font-sans">{selectedAlert.title}</h3>
                <p className="text-xs text-slate-400 mt-1 font-sans leading-relaxed">
                  {selectedAlert.description}
                </p>
              </div>

              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 space-y-2 text-[11px]">
                <div className="flex justify-between">
                  <span className="text-slate-500">Alert ID:</span>
                  <span className="text-slate-200">{selectedAlert.alert_id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Threat Type:</span>
                  <span className="text-cyan-300">{selectedAlert.threat_type}</span>
                </div>
                {selectedAlert.signature_id && (
                  <div className="flex justify-between">
                    <span className="text-slate-500">Target Signature:</span>
                    <span className="text-slate-200">{selectedAlert.signature_id}</span>
                  </div>
                )}
                <div className="flex justify-between">
                  <span className="text-slate-500">Current Status:</span>
                  <span className="text-amber-300 font-bold">{selectedAlert.status}</span>
                </div>
              </div>

              {/* Status Action Buttons */}
              <div className="space-y-2 pt-2">
                <span className="text-slate-400 text-[10px] uppercase block">Update Incident Status:</span>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={() => handleStatusUpdate(selectedAlert.alert_id, 'INVESTIGATING')}
                    className="py-1.5 px-2 rounded bg-amber-950/80 hover:bg-amber-900 text-amber-300 border border-amber-500/40 text-xs font-semibold"
                  >
                    Investigating
                  </button>
                  <button
                    onClick={() => handleStatusUpdate(selectedAlert.alert_id, 'RESOLVED')}
                    className="py-1.5 px-2 rounded bg-emerald-950/80 hover:bg-emerald-900 text-emerald-300 border border-emerald-500/40 text-xs font-semibold"
                  >
                    Resolve Incident
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="text-center text-xs text-slate-500 py-32 font-mono">
              Select an alert from the table to inspect telemetry details.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
